# config/routes.yaml

hello_the_world:
    path:       /contactSheet
    controller: App\Controller\contactSheet::index

contact:
    path:       /contact
    controller: App\Controller\ContactController::contact